var data = [
	//各种都能贷
	[
		{
			"img":"img/anl1.jpg",
			"purpose":"装修贷款",
			"usageNote":"0抵押0担保，100万0利率装修专项贷款"
		},
		{
			"img":"img/anl1.jpg",
			"purpose":"资金周转贷",
			"usageNote":"最快当天放款，贷款10万月利息低至260元"
		},
		{
			"img":"img/anl1.jpg",
			"purpose":"创业贷款",
			"usageNote":"只需5分钟，轻松搞定50万创业资金"
		},
		{
			"img":"img/anl1.jpg",
			"purpose":"经营贷款",
			"usageNote":"额度高达500万，随借随还先息后本"
		},
		{
			"img":"img/anl1.jpg",
			"purpose":"购房贷款",
			"usageNote":"先息后本月供1000元，无压力轻松买房"
		},
		{
			"img":"img/anl1.jpg",
			"purpose":"购车贷款",
			"usageNote":"0首付0利率，一个电话贷款开新车"
		},
		{
			"img":"img/anl1.jpg",
			"purpose":"结婚贷款",
			"usageNote":"爱家分期30万，每月利率2.6‰"
		},
		{
			"img":"img/anl1.jpg",
			"purpose":"旅游贷款",
			"usageNote":"3年循环授信，提现10万加刷卡20万"
		}
	],
	//我们的优势
	[
		{
			"img":"img/anl1.jpg",
			"purpose":"高额度",
			"usageNote":"针对个人定制方案，放款更多！"
		},
		{
			"img":"img/anl2.jpg",
			"purpose":"放款快速",
			"usageNote":"高效率服务，放款快！"
		},
		{
			"img":"img/anl3.jpg",
			"purpose":"门槛低",
			"usageNote":"资质问题？征信问题？都有解决方法。"
		},
		{
			"img":"img/anl4.jpg",
			"purpose":"利率低",
			"usageNote":"渠道多，选择更广！"
		}
	],
	//我们的服务
	[
		[
			{"title":"信用卡提额","status":true},
			[
				{
					"img":"img/anl1.jpg",
					"purpose":"申请容易",
					"usageNote":"电话/网上申请"	
				},
				{
					"img":"img/anl1.jpg",
					"purpose":"当天放款",
					"usageNote":"电话/网上申请"	
				},
				{
					"img":"img/anl1.jpg",
					"purpose":"超低利率",
					"usageNote":"先息后本无压力"	
				},
				{
					"img":"img/anl1.jpg",
					"purpose":"灵活计息",
					"usageNote":"可以按天按月计息"
				}
			]
		],
		[
			{"title":"信用贷款","status":false},
			[
				{
					"img":"img/anl1.jpg",
					"purpose":"申请容易",
					"usageNote":"电话/网上申请"	
				},
				{
					"img":"img/anl1.jpg",
					"purpose":"无需担保",
					"usageNote":"信用是通行证"	
				},
				{
					"img":"img/anl1.jpg",
					"purpose":"贷款额高",
					"usageNote":"最高可贷50万"	
				},
				{
					"img":"img/anl1.jpg",
					"purpose":"放贷快速",
					"usageNote":"最快1天放贷"
				}
			]
		],
		[
			{"title":"房产贷款","status":false},
			[
				{
					"img":"img/anl1.jpg",
					"purpose":"申请容易",
					"usageNote":"电话/网上申请"	
				},
				{
					"img":"img/anl1.jpg",
					"purpose":"利率优惠",
					"usageNote":"最低可享7折"	
				},
				{
					"img":"img/anl1.jpg",
					"purpose":"超长年限",
					"usageNote":"最长可达30年"	
				},
				{
					"img":"img/anl1.jpg",
					"purpose":"一次审批",
					"usageNote":"按天计息/循环使用"
				}
			]
		],
		[
			{"title":"汽车贷款","status":false},
			[
				{
					"img":"img/anl1.jpg",
					"purpose":"申请容易",
					"usageNote":"电话/网上申请"	
				},
				{
					"img":"img/anl1.jpg",
					"purpose":"放款迅速",
					"usageNote":"最快一小时放款"	
				},
				{
					"img":"img/anl1.jpg",
					"purpose":"手续简便",
					"usageNote":"随借随还/按天计息"	
				},
				{
					"img":"img/anl1.jpg",
					"purpose":"贷款成数高",
					"usageNote":"最高评估价达100%"
				}
			]
		],
		[
			{"title":"企业贷款","status":false},
			[
				{
					"img":"img/anl1.jpg",
					"purpose":"申请容易",
					"usageNote":"电话/网上申请"	
				},
				{
					"img":"img/anl1.jpg",
					"purpose":"量身定制",
					"usageNote":"贷多贷少帮您算"	
				},
				{
					"img":"img/anl1.jpg",
					"purpose":"超低利率",
					"usageNote":"低利率/灵活计息"	
				},
				{
					"img":"img/anl1.jpg",
					"purpose":"审批便捷",
					"usageNote":"手续简单/办理快速"
				}
			]
		],
		[
			{"title":"应急贷款","status":false},
			[
				{
					"img":"img/anl1.jpg",
					"purpose":"申请容易",
					"usageNote":"电话/网上申请"	
				},
				{
					"img":"img/anl1.jpg",
					"purpose":"当天放款",
					"usageNote":"电话/网上申请"	
				},
				{
					"img":"img/anl1.jpg",
					"purpose":"超低利率",
					"usageNote":"先息后本无压力"	
				},
				{
					"img":"img/anl1.jpg",
					"purpose":"灵活计息",
					"usageNote":"可以按天按月计息"
				}
			]
		]
	],
	//轮播图
	[
		{
			"src":"img/bg1.jpg",
			"status":true,
		},
		{
			"src":"img/bg2.jpg",
			"status":false,
		},
		{
			"src":"img/bg1.jpg",
			"status":false,
		},
		{
			"src":"img/bg2.jpg",
			"status":false,
		}
	]
]
